"""
Literals that define the resource file format:

BINARY_DELIMITER = 0x00

RESOURCE_SEPARATOR = u'-'

MAGIC_NUMBER = r'OpenRelay'

TIME_STAMP_SEPARATOR = u'_'

MAGIC_VERSION = '1'
"""

BINARY_DELIMITER = 0x00
RESOURCE_SEPARATOR = u'-'
MAGIC_NUMBER = r'OpenRelay'
TIME_STAMP_SEPARATOR = u'_'
MAGIC_VERSION = '1'
